---
- name: Install python3-pip
  apt: name=python3-pip

- name: Install python3-dev
  apt: name=python3-dev

- name: Install npm
  apt: name=npm

- name: Install nodejs
  apt: name=nodejs

- name: Install libmysqlclient-dev
  apt: name=libmysqlclient-dev

- name: Install "configurable-http-proxy" node.js package globally.
  npm:
    name: configurable-http-proxy
    global: yes

- name: Install setuptools
  pip:
    name: setuptools

- name: Install six
  pip:
    name: six

- name: Install wheel
  pip:
    name: wheel

- name: Install jupyter
  pip:
    name: jupyter

- name: Install jupyterhub
  pip:
    name: jupyterhub

- name: Install jupyterlab
  pip:
    name: jupyterlab

- name: Install jupyterlab-git
  pip:
    name: jupyterlab-git

- name: Install oauthenticator
  pip:
    name: oauthenticator

